<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-RepoOps.Worker-ce37334f-2894-45bf-9203-d4d95ef1ede2</UserSecretsId>
  </PropertyGroup>

</Project>
